[tool.poetry]
name = "lru-cache"
version = "0.1.0"
description = "LRU cache implementation"
authors = ["Andrii"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
